### ISSUE TITLE
Index out of bound exception

### ISSUE THREAD

**Issue by palanivelpandian** [juliengk/go-netfilter#1]
fmt.Println(portCheckLinux("22", "INPUT"))
ListOutput, err = ipt.List("filter", &opts) <-- this line Index out of bound exception

**Comment by juliengk** [comment]
have you declared opts?

**Comment by ghost** [comment]
fixed the prob. Let me know if that work for you. Thanks

**Comment by palanivelpandian** [comment]
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/juliengk/go-netfilter/iptables.(*ListOptions).CreateListChain(0xc000043f70, 0x503868, 0x6, 0xc00001e0c6, 0x5, 0xc00001e100, 0x35, 0x0, 0x0, 0x0, ...)
        C:/Users/rocky/go/src/github.com/juliengk/go-netfilter/iptables/iptables.go:363 +0x2c5
github.com/juliengk/go-netfilter/iptables.(*IPTables).runList(0xc00000c080, 0x503868, 0x6, 0xc000043f70, 0xc00007a000, 0x6, 0x8, 0x8, 0x4e8c20, 0xc00000c080)
        C:/Users/rocky/go/src/github.com/juliengk/go-netfilter/iptables/iptables.go:329 +0x458
github.com/juliengk/go-netfilter/iptables.(*IPTables).List(0xc00000c080, 0x503868, 0x6, 0xc00006cf70, 0x0, 0xc00005a1b0, 0x503d3b)
        C:/Users/rocky/go/src/github.com/juliengk/go-netfilter/iptables/iptables.go:109 +0x1e7
main.main()
        D:/GoSamples/src/Open Port check Linux/t.go:24 +0x111

**Comment by ghost** [comment]
HEAD of your local copy of the repo point to which commit?
